apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-subscriber
  namespace: event-driven-samples
spec:
  selector:
    matchLabels:
      app: simple-subscriber
  template:
    metadata:
      labels:
        app: simple-subscriber
    spec:
      serviceAccountName: event-driven-samples-mi-sa
      containers:
      - name: simple-subscriber
        image: eventdrivensamples.azurecr.io/simple-subscriber:latest
        resources:
          limits:
            memory: "512Mi"
        env:
        - name: SimplePublisher__Namespace
          value: "[YOUR SERVICE BUS NAMESPACE HERE]"
        - name: SimplePublisher__QueueName
          value: "[YOUR PRE-CREATED QUEUE HERE]"
        - name: SimpleSubscriber__PrefetchCount
          value: "0"
        - name: SimpleSubscriber__MaxConcurrentCalls
          value: "16"
        - name: SimpleSubscriber__PerfTimerWindowInMs
          value: "1000"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=[YOUR APP INSIGHTS KEY HERE]"
        - name: Logging__Console__FormatterName
          value: "simple"
        - name: Logging__Console__FormatterOptions__IncludeScopes
          value: "true"
        - name: Logging__Console__FormatterOptions__TimestampFormat
          value: "yyy-MM-dd HH:mm:ss.fff "
        - name: Logging__Console__FormatterOptions__SingleLine
          value: "true"
